package("$NAME$")
    set_homepage("$HOMEPAGE$")
    set_description("$DESC$")
    set_license("Apache-2.0")

    add_urls("$REMOTE$")

    -- versions
    -- versions.txt is generated by the release workflow
    add_versionfiles(path.join(os.scriptdir(), "versions.txt"))

    if $HEADERONLY_BOOLEAN$ then
        set_kind("headeronly")
    end

    -- export symbols
    if is_plat("windows") and is_kind("shared") then
        add_rules("utils.symbols.export_all")
    end

    add_rules("utils.install.cmake_importfiles")
    add_rules("utils.install.pkgconfig_importfiles")

    on_load( function (package)
        if package:debug() then
            package:add("defines", "OX_DEBUG")
        end
    end)

    on_install( function (package)
        import("package.tools.xmake").install(package)
    end)

    on_test( function (package)

    end)
